### ISSUE TITLE
The References

### ISSUE THREAD

**Issue by XP-3741** [lryan599/2DNesting#1]
Can you tell me the references? It's hard to understand just by looking at the program. Thank you.

**Comment by lryan599** [comment]
> Can you tell me the references? It's hard to understand just by looking at the program. Thank you.

你是说这个项目的依赖吗？我使用了大量的开源项目，其中部分已经放到本git上，包括lib和dll文件。具体包括：

- [CGAL](https://github.com/CGAL/cgal) 5.6.1，你需要确保能正确使用CGAL，下载相关的所有依赖，包括libgmp，libmpfr等，详情请参阅CGAL项目中的介绍，**确保你能先跑一个CGAL的demo**。
- Boost 1.84，著名的C++库，请前往官网下载。
- Qt 6.5.3，需要Qt中的如下模组：core，gui，widgets，opengl，openglwidgets，svg，xml，charts，请前往Qt官网，参阅Qt的文档进行安装。
- [libdxfrw](https://github.com/LibreCAD/libdxfrw)，用于简单地解析dxf文件。
- [svg_helper](https://github.com/sorrowfeng/svgHelper)，用于简单地解析svg文件，已包含在本git中（svg_helper.h，svg_helper.cpp）。
- [rapidcsv](https://github.com/d99kris/rapidcsv)，用于简单地解析csv文件，已包含在本git中（csv.h）。
- [wyhash](https://github.com/wangyi-fudan/wyhash)，使用了该项目wyhash.h，已包含在本git中。
- [emhash](https://github.com/ktprime/emhash) 2.1.0，使用了该项目的lru_size.h，已包含在本git中。

请使用C++17版本。感谢以上开源项目的作者。未尽事宜请继续提问。

**Comment by XP-3741** [comment]
谢谢答复，确实在配置上不清楚依赖库出现了许多问题。还有就是我想请问实现排料算法时有没有啥参考文献，也就是使用的方法，比如怎样实现的NFP。谢谢

**Comment by lryan599** [comment]
> 谢谢答复，确实在配置上不清楚依赖库出现了许多问题。还有就是我想请问实现排料算法时有没有啥参考文献，也就是使用的方法，比如怎样实现的NFP。谢谢

本项目中排样算法在nesting.h和nesting.cpp中实现，没有专门的文档。这两个文件简单地使用了闵可夫斯基向量和计算NFP。本项目的排样算法实际上是[文献](https://doi.org/10.1016/j.ejor.2013.06.020)提出的算法的改良，该文献没有找到公开的代码，但可以从该文献理解这类排样算法的思路。

**Comment by XP-3741** [comment]
十分感谢
